### ISSUE TITLE
Doubled first character of proposed sequence

### ISSUE THREAD

**Issue by PiotrDabrowskey** [zxqfl/tabnine-intellij#1]
When I try to use autocompletion (either by hitting tab, enter or choosing the option with a mouse-click), the first character of the proposed sequence is being doubled.

My code is, say `variable=T`, I hit tab and `True` is the first proposed option, but when I accept it, the resulting line is `variable=TTrue`.

Here's how it looks:
![tabnine](https://user-images.githubusercontent.com/9080823/63519812-e0da2300-c4f3-11e9-8b16-b94cecba9905.gif)

Versions:
TabNine 0.1.2
PyCharm 2019.2 (Community Edition)

<details><summary>More PyCharm details</summary>

Build #PC-192.5728.105, built on July 23, 2019
Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.0.0-25-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1998M
Cores: 6
Registry: 
Non-Bundled Plugins: com.jetbrains.plugins.ini4idea, com.ppolivka.gitlabprojects, com.tabnine.TabNine, mobi.hsz.idea.gitignore, org.intellij.plugins.markdown, BashSupport, ru.adelf.idea.dotenv, zielu.gittoolbox

</details>

**Comment by zxqfl** [comment]
That looks pretty annoying. Does restarting the IDE temporarily fix the issue?

**Comment by PiotrDabrowskey** [comment]
Yes it is, it made me not to use the extension until it gets solved.

I had this problem a week ago, when I first installed it. I decided to disable the plugin as I thought it may be a somewhat common issue. Today my friend showed me that it works for him without any problems, so I gave it another try, but without a luck.

In the meantime I restarted my PC, so we can say I did try restarting the IDE. Also tried to disable and reenable the plugin (with a mandatory restarts between steps).

Do you think it may be a conflict between plugins? Tomorrow I'll try to disable all the other plugins and let you know how it behaves.

**Comment by RidgeA** [comment]
I've also experienced this issue right after installing the plugin, the IDE relaunch solved it.

**Comment by PiotrDabrowskey** [comment]
@RidgeA your hint was helpful. Today it started working for me after the IDE restart, but it broke immediately after running `TabNine::config`.

From whatever reason it didn't broke on the first try after opening the config, but in each next autocompletions the problem remains. @zxqfl my quick guess is that the plugin works properly until opening the config.

The gif presents this behavior (by the way after I stopped recording even `TabNine::version` broke as I got `TTabNine::vversion`):
![tabnine1](https://user-images.githubusercontent.com/9080823/63576024-ad4ad780-c58b-11e9-882c-cb2c45933b87.gif)

As a side not: the gif also presents another problem that was hard for me to reproduce - in the line 39 my first input got partially removed: my code was `vvariable `, from autocompletion list I choose `variable = True` and the result was: `vvariablvariable = True`, while it should be `vvariable variable = True` (not proper in a Pythonic meaning but without any characters removed). I think it may be the same issue.

**Comment by Shagrat** [comment]
I have same issue. 

> PyCharm 2019.2.1 (Professional Edition)
Build #PY-192.6262.63, built on August 22, 2019
Runtime version: 11.0.3+12-b304.39 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.19.0-5-amd64
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: 
Non-Bundled Plugins: com.leinardi.pycharm.pylint, com.tabnine.TabNine, net.ashald.envfile, net.seesharpsoft.intellij.plugins.csv, BashSupport, NodeJS, org.jetbrains.plugins.vue, ru.adelf.idea.dotenv

**Comment by zxqfl** [comment]
I wasn't able to reproduce the issue by typing TabNine::version. However I've added code to try to detect this situation and automatically restart TabNine in the background: https://github.com/zxqfl/tabnine-intellij/commit/1dae1f37cad59a6a5c4d33d157b57d1d3c151c5b

The update is pending JetBrains approval — please try 0.1.3 once it's approved by JetBrains and check if it fixes the issue.

**Comment by PiotrDabrowskey** [comment]
Cool, I'll let you know if it fixes the problem.

**Comment by PiotrDabrowskey** [comment]
`0.1.3` seemingly fixes the issue, thanks!
